name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-rust:
    name: Build Rust Project (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Build Rust
      run: cargo build --release
      
    - name: Upload Rust artifacts
      uses: actions/upload-artifact@v4
      with:
        name: osu-beatmap-addtime-migrate-rust-${{ matrix.os }}
        path: |
          target/release/main.exe
          target/release/main

  build-dotnet:
    name: Build .NET Project (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Build .NET
      run: dotnet publish --configuration Release --runtime ${{ matrix.os == 'windows-latest' && 'win-x64' || 'linux-x64' }} --self-contained true
      
    - name: Upload .NET artifacts
      uses: actions/upload-artifact@v4
      with:
        name: osu-beatmap-addtime-migrate-dotnet-${{ matrix.os }}
        path: |
          **/bin/Release/net8.0/${{ matrix.os == 'windows-latest' && 'win-x64' || 'linux-x64' }}/publish/*

  create-release:
    name: Create Release
    needs: [build-rust, build-dotnet]
    runs-on: ubuntu-latest

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Release Packages
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        # Create Windows package
        mkdir -p release-package-windows
        cp osu-beatmap-addtime-migrate-rust-windows-latest/main.exe release-package-windows/
        cp -r osu-beatmap-addtime-migrate-dotnet-windows-latest/* release-package-windows/
        zip -r "osu-beatmap-addtime-migrate-${VERSION}-windows-x64.zip" release-package-windows/
        
        # Create Linux package
        mkdir -p release-package-linux
        cp osu-beatmap-addtime-migrate-rust-ubuntu-latest/main release-package-linux/
        cp -r osu-beatmap-addtime-migrate-dotnet-ubuntu-latest/* release-package-linux/
        chmod +x release-package-linux/main
        chmod +x release-package-linux/OsuRealmWriter
        zip -r "osu-beatmap-addtime-migrate-${VERSION}-linux-x64.zip" release-package-linux/
      shell: bash
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        files: |
          osu-beatmap-addtime-migrate-*-windows-x64.zip
          osu-beatmap-addtime-migrate-*-linux-x64.zip